# Generated by Django 5.2.11 on 2026-05-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0002_bill_grand_total_billitem_total_alter_billitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
