# Generated by Django 5.2.11 on 2026-05-27 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0003_alter_billitem_quantity'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_items', to='products.product'),
        ),
    ]
