# Generated by Django 5.2.11 on 2026-06-30 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0004_alter_billitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_number', models.CharField(max_length=20, unique=True)),
                ('customer_name', models.CharField(default='Walk-in Customer', max_length=100)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='customer_name',
            field=models.CharField(default='Walk-in Customer', max_length=100),
        ),
        migrations.CreateModel(
            name='HoldBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hold_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billings.holdbill')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billings.product')),
            ],
        ),
    ]
